name: Deploy Java Spring Boot Application to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven (clean install then clean package)
        run: |
          mvn clean install
          mvn clean package

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # Definindo o diretório de trabalho e repositório
            REPO_DIR="/home/ubuntu/Clinica-Medica"
            
            # Verificando se o diretório existe, e atualizando o repositório ou clonando-o
            if [ ! -d "$REPO_DIR" ]; then
              echo "Clonando o repositório..."
              git clone https://github.com/ThiagoMachado2/ClinicaMedica.git $REPO_DIR
            else
              echo "Atualizando o repositório..."
              cd $REPO_DIR
              git pull origin main
            fi

            # Navegando para o diretório do repositório
            cd $REPO_DIR
            
            # Atualizando dependências e construindo o projeto
            echo "Construindo o projeto..."
            mvn clean install -DskipTests
            mvn clean package -DskipTests
            
            # Executando a aplicação em segundo plano
            echo "Iniciando a aplicação..."
            nohup java -jar target/clinica-0.0.1-SNAPSHOT.jar &

            echo "Deploy concluído com sucesso!"
