name: Deploy Java Spring Boot Application to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven (clean install then clean package)
        run: mvn clean install && mvn clean package

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/
            if [ ! -d "Clinica-Medica" ]; then
              git clone https://github.com/ThiagoMachado2/ClinicaMedica.git
            else
              cd Clinica-Medica
              git pull origin main
            fi
            cd Clinica-Medica
            mvn clean install  
            mvn clean package  
            nohup java -jar target/clinica-0.0.1-SNAPSHOT.jar & 
